<?php

/**
 * Implements hook_theme().
 */
function nttcom_calendar_theme($existing, $type, $theme, $path) {
  return [
    'nttcom_block_calendar' => [
      'render element' => 'children',
      'template' => 'nttcom-calendar-block',
    ],
    'nttcom_block_calendar_form' => [
      'render element' => 'form',
      'template' => 'nttcom-calendar-block-form',
    ]
  ];
}

/**
 * Implements hook_preprocess_HOOK().
 */
function nttcom_calendar_preprocess_views_view_fullcalendar(array &$variables) {
  $variables['#attached']['library'][] ='nttcom_calendar/nttcom.fullcalendar';
}
