<?php

/**
 * @file
 * Dashboard.
 * @TODO: icons should be swapable + some other approach then classes
 * @TODO: create example yaml
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_theme().
 */
function dashboard_theme($existing, $type, $theme, $path) {
  return [
    'dashboard' => [
      'variables' => ['title' => '', 'dashboard_menu' => '']
    ]
  ];
}

/**
 * Get one config value.
 *
 * @param string $name
 *   The key or title.
 * @param null $default_value
 *   Default value.
 *
 * @return mixed|null
 *   Returns data.
 */
function dashboard_get($name, $default_value = NULL) {
  $data = dashboard_load_config();
  return isset($data[$name]) ? $data[$name] : $default_value;
}

/**
 * Load config from plugin manager.
 */
function dashboard_load_config() {
  $data = \Drupal::service('plugin.manager.dashboard')->getDefinitions();
  return $data;
}

/**
 * Legacy icon map to fontawesome.
 */
function _dashboard_legacy_icon_map() {
  return [
    "file" => "file-o",
    "bars" => "bars",
    "pen" => "pencil",
    "hammer" => "gear",
    "menu" => "bars",
    "profile" => "user-o",
    "users" => "users",
    "bookmarks" => "bookmark",
    "numbered-list" => "list",
  ];
}

function dashboard_form_alter(&$form, FormStateInterface $form_state) {
    $form['tracking']['parameters']=[
        '#access' => false
    ];
}